//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Negocio.ServicioWCF {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="AportacionesIMSS", Namespace="http://schemas.datacontract.org/2004/07/WCFAlumno")]
    [System.SerializableAttribute()]
    public partial class AportacionesIMSS : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal cesantiaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal enfermedadMaternidadField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal infonavitField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal invalidezVidaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal retiroField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal cesantia {
            get {
                return this.cesantiaField;
            }
            set {
                if ((this.cesantiaField.Equals(value) != true)) {
                    this.cesantiaField = value;
                    this.RaisePropertyChanged("cesantia");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal enfermedadMaternidad {
            get {
                return this.enfermedadMaternidadField;
            }
            set {
                if ((this.enfermedadMaternidadField.Equals(value) != true)) {
                    this.enfermedadMaternidadField = value;
                    this.RaisePropertyChanged("enfermedadMaternidad");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal infonavit {
            get {
                return this.infonavitField;
            }
            set {
                if ((this.infonavitField.Equals(value) != true)) {
                    this.infonavitField = value;
                    this.RaisePropertyChanged("infonavit");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal invalidezVida {
            get {
                return this.invalidezVidaField;
            }
            set {
                if ((this.invalidezVidaField.Equals(value) != true)) {
                    this.invalidezVidaField = value;
                    this.RaisePropertyChanged("invalidezVida");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal retiro {
            get {
                return this.retiroField;
            }
            set {
                if ((this.retiroField.Equals(value) != true)) {
                    this.retiroField = value;
                    this.RaisePropertyChanged("retiro");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TablaISR", Namespace="http://schemas.datacontract.org/2004/07/WCFAlumno")]
    [System.SerializableAttribute()]
    public partial class TablaISR : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal LimSupField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal cuotaFijaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal excedenteField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal impuestoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal limInfField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal subsidioField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal LimSup {
            get {
                return this.LimSupField;
            }
            set {
                if ((this.LimSupField.Equals(value) != true)) {
                    this.LimSupField = value;
                    this.RaisePropertyChanged("LimSup");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal cuotaFija {
            get {
                return this.cuotaFijaField;
            }
            set {
                if ((this.cuotaFijaField.Equals(value) != true)) {
                    this.cuotaFijaField = value;
                    this.RaisePropertyChanged("cuotaFija");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal excedente {
            get {
                return this.excedenteField;
            }
            set {
                if ((this.excedenteField.Equals(value) != true)) {
                    this.excedenteField = value;
                    this.RaisePropertyChanged("excedente");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal impuesto {
            get {
                return this.impuestoField;
            }
            set {
                if ((this.impuestoField.Equals(value) != true)) {
                    this.impuestoField = value;
                    this.RaisePropertyChanged("impuesto");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal limInf {
            get {
                return this.limInfField;
            }
            set {
                if ((this.limInfField.Equals(value) != true)) {
                    this.limInfField = value;
                    this.RaisePropertyChanged("limInf");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal subsidio {
            get {
                return this.subsidioField;
            }
            set {
                if ((this.subsidioField.Equals(value) != true)) {
                    this.subsidioField = value;
                    this.RaisePropertyChanged("subsidio");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServicioWCF.IAlumnoWCF")]
    public interface IAlumnoWCF {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAlumnoWCF/CalcularIMSS", ReplyAction="http://tempuri.org/IAlumnoWCF/CalcularIMSSResponse")]
        Negocio.ServicioWCF.AportacionesIMSS CalcularIMSS(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAlumnoWCF/CalcularIMSS", ReplyAction="http://tempuri.org/IAlumnoWCF/CalcularIMSSResponse")]
        System.Threading.Tasks.Task<Negocio.ServicioWCF.AportacionesIMSS> CalcularIMSSAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAlumnoWCF/CalcularISR", ReplyAction="http://tempuri.org/IAlumnoWCF/CalcularISRResponse")]
        Negocio.ServicioWCF.TablaISR CalcularISR(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAlumnoWCF/CalcularISR", ReplyAction="http://tempuri.org/IAlumnoWCF/CalcularISRResponse")]
        System.Threading.Tasks.Task<Negocio.ServicioWCF.TablaISR> CalcularISRAsync(int id);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IAlumnoWCFChannel : Negocio.ServicioWCF.IAlumnoWCF, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class AlumnoWCFClient : System.ServiceModel.ClientBase<Negocio.ServicioWCF.IAlumnoWCF>, Negocio.ServicioWCF.IAlumnoWCF {
        
        public AlumnoWCFClient() {
        }
        
        public AlumnoWCFClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public AlumnoWCFClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AlumnoWCFClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AlumnoWCFClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public Negocio.ServicioWCF.AportacionesIMSS CalcularIMSS(int id) {
            return base.Channel.CalcularIMSS(id);
        }
        
        public System.Threading.Tasks.Task<Negocio.ServicioWCF.AportacionesIMSS> CalcularIMSSAsync(int id) {
            return base.Channel.CalcularIMSSAsync(id);
        }
        
        public Negocio.ServicioWCF.TablaISR CalcularISR(int id) {
            return base.Channel.CalcularISR(id);
        }
        
        public System.Threading.Tasks.Task<Negocio.ServicioWCF.TablaISR> CalcularISRAsync(int id) {
            return base.Channel.CalcularISRAsync(id);
        }
    }
}
