//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entidades
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class instituto_tichEntities1 : DbContext
    {
        public instituto_tichEntities1()
            : base("name=instituto_tichEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<alumnos> alumnos { get; set; }
        public virtual DbSet<estados> estados { get; set; }
        public virtual DbSet<estatus_alumnos> estatus_alumnos { get; set; }
    }
}
